### ISSUE TITLE
Add set math RHS functions to manual

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/Release-Support#8]
These were added in 9.6.1 for JSoar compatibility, and we didn't have the time to introduce new manual sections for them.

**Comment by garfieldnate** [comment]
@marinier The API of set-mac is a bit more complex than I thought. If anyone at ST could provide an example usage with the expected output, that would be very helpful.

**Comment by garfieldnate** [comment]
That comment is actually a copy-paste error from a different function, `set-stdev`. Here's the documentation from `set_mac`, which implements `set-mac`:

```c++
/*
 * Set-based multiply accumulates.
 *
 * Expects four parameters:
 *  - The ID of a set
 *  - Attribute name for the item that contains two factors to multiply
 *  - The name of one of the factors
 *  - The name of the other factor
 *
 * The algorithm moves through each item and multiplies its two factors, accumulating the result
 *  across all items (thus multiply-accumulate)
 *
 * The return value is only not NIL if the fn returns an error symbol.
 */
```

This is not quite clear to me. For the factors, do we have an attribute that's a symbol WME with more attributes that contain the factors to multiply? So `^att-foo.a` and `^att-foo.b` could be the factors?

And then how is the multiply and accumulate over the set done? Is it a sum of a*s_i + b*s_i for s_i in the set S? This isn't clear to me.

If ST isn't using it, though, I'd just as soon remove it.

**Comment by marinier** [comment]
Ah ok. I doubt anyone is using at soartech, so you could remove it. If i
had to guess I'd say it was used by Soar Auto, but that is now defunct.

I believe it was added in an attempt to have a complete group functions for
acting on sets, since soar working memory tends to have lots of sets so it
seemed like there should be methods for operating on them. If you think
that's useful then I could make an example for you showing how to use it.
